import { ref, type SchemaMap } from '../../types';

export const customerSchemas: SchemaMap = {
  Customer: {
    type: 'object',
    description: 'A WordPress user with the `customer` role plus WooCommerce billing/shipping data.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 57 },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      date_modified: { type: 'string', format: 'date-time', readOnly: true, nullable: true },
      date_modified_gmt: { type: 'string', format: 'date-time', readOnly: true, nullable: true },
      email: { type: 'string', format: 'email', example: 'asha@example.com' },
      first_name: { type: 'string', example: 'Asha' },
      last_name: { type: 'string', example: 'Iyer' },
      role: { type: 'string', readOnly: true, default: 'customer' },
      username: { type: 'string', example: 'asha.iyer' },
      password: {
        type: 'string',
        format: 'password',
        writeOnly: true,
        description: 'Write-only. Omit to have WordPress generate one and email the customer.',
      },
      billing: ref('Address'),
      shipping: ref('Address'),
      is_paying_customer: { type: 'boolean', readOnly: true },
      avatar_url: { type: 'string', format: 'uri', readOnly: true },
      meta_data: { type: 'array', items: ref('MetaData') },
      _links: ref('Links'),
    },
    required: ['email'],
    example: {
      id: 57,
      email: 'asha@example.com',
      first_name: 'Asha',
      last_name: 'Iyer',
      username: 'asha.iyer',
      is_paying_customer: true,
    },
  },

  CustomerDownload: {
    type: 'object',
    readOnly: true,
    description: 'A downloadable file the customer has purchased access to.',
    properties: {
      download_id: { type: 'string' },
      download_url: { type: 'string', format: 'uri' },
      product_id: { type: 'integer' },
      product_name: { type: 'string' },
      download_name: { type: 'string' },
      order_id: { type: 'integer' },
      order_key: { type: 'string' },
      downloads_remaining: { type: 'string', example: 'unlimited' },
      access_expires: { type: 'string', nullable: true, example: 'never' },
      access_expires_gmt: { type: 'string', nullable: true },
      file: {
        type: 'object',
        properties: { name: { type: 'string' }, file: { type: 'string', format: 'uri' } },
      },
      _links: ref('Links'),
    },
  },

  Coupon: {
    type: 'object',
    description: 'A discount coupon and the rules that constrain it.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 310 },
      code: {
        type: 'string',
        description: 'Coupon code. Always stored lowercase.',
        example: 'welcome10',
      },
      amount: {
        type: 'string',
        description: 'Discount value. A percentage when `discount_type` is `percent`.',
        example: '10.00',
      },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      date_modified: { type: 'string', format: 'date-time', readOnly: true },
      date_modified_gmt: { type: 'string', format: 'date-time', readOnly: true },
      discount_type: {
        type: 'string',
        enum: ['percent', 'fixed_cart', 'fixed_product'],
        default: 'fixed_cart',
      },
      description: { type: 'string' },
      date_expires: { type: 'string', format: 'date-time', nullable: true },
      date_expires_gmt: { type: 'string', format: 'date-time', nullable: true },
      usage_count: { type: 'integer', readOnly: true, example: 214 },
      individual_use: { type: 'boolean', default: false, description: 'Cannot be combined with other coupons.' },
      product_ids: { type: 'array', items: { type: 'integer' } },
      excluded_product_ids: { type: 'array', items: { type: 'integer' } },
      usage_limit: { type: 'integer', nullable: true, example: 1000 },
      usage_limit_per_user: { type: 'integer', nullable: true, example: 1 },
      limit_usage_to_x_items: { type: 'integer', nullable: true },
      free_shipping: { type: 'boolean', default: false },
      product_categories: { type: 'array', items: { type: 'integer' } },
      excluded_product_categories: { type: 'array', items: { type: 'integer' } },
      exclude_sale_items: { type: 'boolean', default: false },
      minimum_amount: { type: 'string', example: '999.00' },
      maximum_amount: { type: 'string', example: '' },
      email_restrictions: { type: 'array', items: { type: 'string', format: 'email' } },
      used_by: { type: 'array', readOnly: true, items: { type: 'string' } },
      meta_data: { type: 'array', items: ref('MetaData') },
      _links: ref('Links'),
    },
    required: ['code'],
    example: {
      id: 310,
      code: 'welcome10',
      discount_type: 'percent',
      amount: '10.00',
      individual_use: true,
      usage_limit_per_user: 1,
      minimum_amount: '999.00',
    },
  },
} as const;
