import { ref, type SchemaMap } from '../../types';

export const orderSchemas: SchemaMap = {
  Order: {
    type: 'object',
    description: 'A customer order with its line items, totals, addresses and fulfilment state.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 1042 },
      parent_id: { type: 'integer', default: 0 },
      number: { type: 'string', readOnly: true, example: '1042' },
      order_key: { type: 'string', readOnly: true, example: 'wc_order_qw12ER34ty' },
      created_via: { type: 'string', readOnly: true, example: 'rest-api' },
      version: { type: 'string', readOnly: true, example: '9.4.2' },
      status: {
        type: 'string',
        description:
          'Order status. Plugins may register additional statuses; treat this as an open set.',
        enum: [
          'pending',
          'processing',
          'on-hold',
          'completed',
          'cancelled',
          'refunded',
          'failed',
          'trash',
          'checkout-draft',
        ],
        default: 'pending',
      },
      currency: { type: 'string', description: 'ISO 4217 currency code.', default: 'USD', example: 'INR' },
      currency_symbol: { type: 'string', readOnly: true, example: '₹' },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      date_modified: { type: 'string', format: 'date-time', readOnly: true },
      date_modified_gmt: { type: 'string', format: 'date-time', readOnly: true },
      discount_total: { type: 'string', readOnly: true, example: '250.00' },
      discount_tax: { type: 'string', readOnly: true, example: '0.00' },
      shipping_total: { type: 'string', readOnly: true, example: '99.00' },
      shipping_tax: { type: 'string', readOnly: true, example: '0.00' },
      cart_tax: { type: 'string', readOnly: true, example: '404.82' },
      total: { type: 'string', readOnly: true, example: '2998.00' },
      total_tax: { type: 'string', readOnly: true, example: '404.82' },
      prices_include_tax: { type: 'boolean', readOnly: true },
      customer_id: { type: 'integer', default: 0, description: '0 for guest checkouts.', example: 57 },
      customer_ip_address: { type: 'string', readOnly: true },
      customer_user_agent: { type: 'string', readOnly: true },
      customer_note: { type: 'string', example: 'Leave with the security desk.' },
      billing: ref('Address'),
      shipping: ref('Address'),
      payment_method: { type: 'string', example: 'razorpay' },
      payment_method_title: { type: 'string', example: 'Credit Card (Razorpay)' },
      transaction_id: { type: 'string' },
      date_paid: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
      date_paid_gmt: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
      date_completed: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
      date_completed_gmt: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
      cart_hash: { type: 'string', readOnly: true },
      meta_data: { type: 'array', items: ref('MetaData') },
      line_items: { type: 'array', items: ref('OrderLineItem') },
      tax_lines: { type: 'array', readOnly: true, items: ref('OrderTaxLine') },
      shipping_lines: { type: 'array', items: ref('OrderShippingLine') },
      fee_lines: { type: 'array', items: ref('OrderFeeLine') },
      coupon_lines: { type: 'array', items: ref('OrderCouponLine') },
      refunds: { type: 'array', readOnly: true, items: ref('OrderRefundRef') },
      set_paid: {
        type: 'boolean',
        writeOnly: true,
        description: 'Write-only. Set true on create/update to mark the order paid immediately.',
        default: false,
      },
      _links: ref('Links'),
    },
    example: {
      id: 1042,
      status: 'processing',
      currency: 'INR',
      total: '2998.00',
      customer_id: 57,
      payment_method: 'razorpay',
      payment_method_title: 'Credit Card (Razorpay)',
      billing: {
        first_name: 'Asha',
        last_name: 'Iyer',
        address_1: '221B Residency Road',
        city: 'Bengaluru',
        state: 'KA',
        postcode: '560025',
        country: 'IN',
        email: 'asha@example.com',
      },
      line_items: [{ id: 9, product_id: 799, quantity: 1, total: '2499.00' }],
    },
  },

  OrderLineItem: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      name: { type: 'string', readOnly: true, example: 'Ceramic Pour-Over Kit' },
      product_id: { type: 'integer', example: 799 },
      variation_id: { type: 'integer', default: 0 },
      quantity: { type: 'integer', example: 1 },
      tax_class: { type: 'string' },
      subtotal: { type: 'string', example: '2499.00' },
      subtotal_tax: { type: 'string', readOnly: true },
      total: {
        type: 'string',
        description: 'Line total after discounts. Omit on create to let WooCommerce calculate it.',
        example: '2499.00',
      },
      total_tax: { type: 'string', readOnly: true },
      taxes: { type: 'array', readOnly: true, items: ref('OrderItemTax') },
      meta_data: { type: 'array', items: ref('MetaData') },
      sku: { type: 'string', readOnly: true },
      price: { type: 'number', readOnly: true, example: 2499 },
      image: {
        type: 'object',
        readOnly: true,
        properties: { id: { type: 'string' }, src: { type: 'string', format: 'uri' } },
      },
      parent_name: { type: 'string', nullable: true, readOnly: true },
    },
    required: ['product_id'],
  },

  OrderItemTax: {
    type: 'object',
    readOnly: true,
    properties: {
      id: { type: 'integer', description: 'Tax rate ID.' },
      total: { type: 'string' },
      subtotal: { type: 'string' },
    },
  },

  OrderTaxLine: {
    type: 'object',
    readOnly: true,
    properties: {
      id: { type: 'integer' },
      rate_code: { type: 'string', example: 'IN-KA-GST-1' },
      rate_id: { type: 'integer' },
      label: { type: 'string', example: 'GST' },
      compound: { type: 'boolean' },
      tax_total: { type: 'string' },
      shipping_tax_total: { type: 'string' },
      rate_percent: { type: 'number', example: 18 },
      meta_data: { type: 'array', items: ref('MetaData') },
    },
  },

  OrderShippingLine: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      method_title: { type: 'string', example: 'Standard Delivery' },
      method_id: { type: 'string', example: 'flat_rate' },
      instance_id: { type: 'string', example: '3' },
      total: { type: 'string', example: '99.00' },
      total_tax: { type: 'string', readOnly: true },
      taxes: { type: 'array', readOnly: true, items: ref('OrderItemTax') },
      meta_data: { type: 'array', items: ref('MetaData') },
    },
    required: ['method_id'],
  },

  OrderFeeLine: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      name: { type: 'string', example: 'Gift wrapping' },
      tax_class: { type: 'string' },
      tax_status: { type: 'string', enum: ['taxable', 'none'], default: 'taxable' },
      total: { type: 'string', example: '75.00' },
      total_tax: { type: 'string', readOnly: true },
      taxes: { type: 'array', readOnly: true, items: ref('OrderItemTax') },
      meta_data: { type: 'array', items: ref('MetaData') },
    },
    required: ['name'],
  },

  OrderCouponLine: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      code: { type: 'string', example: 'welcome10' },
      discount: { type: 'string', readOnly: true, example: '250.00' },
      discount_tax: { type: 'string', readOnly: true },
      meta_data: { type: 'array', items: ref('MetaData') },
    },
    required: ['code'],
  },

  OrderRefundRef: {
    type: 'object',
    readOnly: true,
    properties: {
      id: { type: 'integer' },
      reason: { type: 'string' },
      total: { type: 'string', example: '-2499.00' },
    },
  },

  OrderRefund: {
    type: 'object',
    description: 'A refund against an order. Creating one may also trigger a gateway refund.',
    properties: {
      id: { type: 'integer', readOnly: true },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      amount: { type: 'string', description: 'Total refund amount. Required unless line items are supplied.', example: '2499.00' },
      reason: { type: 'string', example: 'Damaged on arrival' },
      refunded_by: { type: 'integer', description: 'User ID that issued the refund.' },
      refunded_payment: { type: 'boolean', readOnly: true },
      meta_data: { type: 'array', items: ref('MetaData') },
      line_items: { type: 'array', items: ref('OrderLineItem') },
      api_refund: {
        type: 'boolean',
        writeOnly: true,
        default: true,
        description: 'When true, also refund via the payment gateway API if it supports it.',
      },
      api_restock: {
        type: 'boolean',
        writeOnly: true,
        default: true,
        description: 'When true, restock refunded line items.',
      },
      _links: ref('Links'),
    },
  },

  OrderNote: {
    type: 'object',
    description: 'A note on an order. Customer notes are emailed to the buyer.',
    properties: {
      id: { type: 'integer', readOnly: true },
      author: { type: 'string', readOnly: true, example: 'system' },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      note: { type: 'string', example: 'Shipped via BlueDart, AWB 1234567890.' },
      customer_note: { type: 'boolean', default: false },
      added_by_user: { type: 'boolean', writeOnly: true, default: false },
      _links: ref('Links'),
    },
    required: ['note'],
  },
} as const;
