import { ref, type SchemaMap } from '../../types';

export const productSchemas: SchemaMap = {
  Product: {
    type: 'object',
    description: 'A catalogue product: simple, grouped, external/affiliate or variable.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 799 },
      name: { type: 'string', example: 'Ceramic Pour-Over Kit' },
      slug: { type: 'string', example: 'ceramic-pour-over-kit' },
      permalink: { type: 'string', format: 'uri', readOnly: true },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      date_modified: { type: 'string', format: 'date-time', readOnly: true },
      date_modified_gmt: { type: 'string', format: 'date-time', readOnly: true },
      type: {
        type: 'string',
        enum: ['simple', 'grouped', 'external', 'variable'],
        default: 'simple',
      },
      status: {
        type: 'string',
        enum: ['draft', 'pending', 'private', 'publish'],
        default: 'publish',
      },
      featured: { type: 'boolean', default: false },
      catalog_visibility: {
        type: 'string',
        enum: ['visible', 'catalog', 'search', 'hidden'],
        default: 'visible',
      },
      description: { type: 'string', description: 'Full HTML description.' },
      short_description: { type: 'string', description: 'Excerpt shown near the add-to-cart box.' },
      sku: { type: 'string', example: 'POUR-CER-01' },
      price: { type: 'string', readOnly: true, description: 'Current effective price.', example: '2499.00' },
      regular_price: { type: 'string', example: '2999.00' },
      sale_price: { type: 'string', example: '2499.00' },
      date_on_sale_from: { type: 'string', format: 'date-time', nullable: true },
      date_on_sale_from_gmt: { type: 'string', format: 'date-time', nullable: true },
      date_on_sale_to: { type: 'string', format: 'date-time', nullable: true },
      date_on_sale_to_gmt: { type: 'string', format: 'date-time', nullable: true },
      price_html: { type: 'string', readOnly: true },
      on_sale: { type: 'boolean', readOnly: true },
      purchasable: { type: 'boolean', readOnly: true },
      total_sales: { type: 'integer', readOnly: true, example: 412 },
      virtual: { type: 'boolean', default: false, description: 'No shipping required.' },
      downloadable: { type: 'boolean', default: false },
      downloads: { type: 'array', items: ref('ProductDownload') },
      download_limit: { type: 'integer', default: -1, description: '-1 means unlimited.' },
      download_expiry: { type: 'integer', default: -1, description: 'Days until expiry, -1 for never.' },
      external_url: { type: 'string', format: 'uri', description: 'External/affiliate products only.' },
      button_text: { type: 'string', description: 'External/affiliate products only.' },
      tax_status: { type: 'string', enum: ['taxable', 'shipping', 'none'], default: 'taxable' },
      tax_class: { type: 'string', example: '' },
      manage_stock: {
        description: 'Boolean on products; variations may also inherit with the string "parent".',
        oneOf: [{ type: 'boolean' }, { type: 'string', enum: ['parent'] }],
        default: false,
      },
      stock_quantity: { type: 'integer', nullable: true, example: 24 },
      stock_status: {
        type: 'string',
        enum: ['instock', 'outofstock', 'onbackorder'],
        default: 'instock',
      },
      backorders: { type: 'string', enum: ['no', 'notify', 'yes'], default: 'no' },
      backorders_allowed: { type: 'boolean', readOnly: true },
      backordered: { type: 'boolean', readOnly: true },
      low_stock_amount: { type: 'integer', nullable: true },
      sold_individually: { type: 'boolean', default: false },
      weight: { type: 'string', example: '1.4' },
      dimensions: ref('Dimensions'),
      shipping_required: { type: 'boolean', readOnly: true },
      shipping_taxable: { type: 'boolean', readOnly: true },
      shipping_class: { type: 'string' },
      shipping_class_id: { type: 'integer', readOnly: true },
      reviews_allowed: { type: 'boolean', default: true },
      average_rating: { type: 'string', readOnly: true, example: '4.67' },
      rating_count: { type: 'integer', readOnly: true, example: 18 },
      related_ids: { type: 'array', readOnly: true, items: { type: 'integer' } },
      upsell_ids: { type: 'array', items: { type: 'integer' } },
      cross_sell_ids: { type: 'array', items: { type: 'integer' } },
      parent_id: { type: 'integer', default: 0 },
      purchase_note: { type: 'string' },
      categories: { type: 'array', items: ref('ProductTermRef') },
      tags: { type: 'array', items: ref('ProductTermRef') },
      images: { type: 'array', items: ref('Image') },
      attributes: { type: 'array', items: ref('ProductAttributeValue') },
      default_attributes: { type: 'array', items: ref('ProductDefaultAttribute') },
      variations: { type: 'array', readOnly: true, items: { type: 'integer' } },
      grouped_products: { type: 'array', items: { type: 'integer' } },
      menu_order: { type: 'integer', default: 0 },
      meta_data: { type: 'array', items: ref('MetaData') },
      _links: ref('Links'),
    },
    example: {
      id: 799,
      name: 'Ceramic Pour-Over Kit',
      slug: 'ceramic-pour-over-kit',
      type: 'simple',
      status: 'publish',
      sku: 'POUR-CER-01',
      regular_price: '2999.00',
      sale_price: '2499.00',
      price: '2499.00',
      on_sale: true,
      stock_status: 'instock',
      stock_quantity: 24,
      categories: [{ id: 19, name: 'Brewing', slug: 'brewing' }],
    },
  },


  ProductDownload: {
    type: 'object',
    properties: {
      id: { type: 'string', description: 'Download MD5 hash.', readOnly: true },
      name: { type: 'string', example: 'Brew guide (PDF)' },
      file: { type: 'string', format: 'uri' },
    },
  },

  ProductTermRef: {
    type: 'object',
    description: 'Lightweight category/tag reference embedded inside a product.',
    properties: {
      id: { type: 'integer', example: 19 },
      name: { type: 'string', readOnly: true, example: 'Brewing' },
      slug: { type: 'string', readOnly: true, example: 'brewing' },
    },
    required: ['id'],
  },

  ProductAttributeValue: {
    type: 'object',
    description:
      'An attribute as attached to a product. Global attributes carry an `id`; custom (per-product) attributes carry only a `name`.',
    properties: {
      id: { type: 'integer', description: 'Global attribute ID, 0 for custom attributes.', example: 3 },
      name: { type: 'string', example: 'Size' },
      position: { type: 'integer', default: 0 },
      visible: { type: 'boolean', default: false, description: 'Show on the product page.' },
      variation: { type: 'boolean', default: false, description: 'Usable for variations.' },
      options: { type: 'array', items: { type: 'string' }, example: ['S', 'M', 'L'] },
    },
  },

  ProductDefaultAttribute: {
    type: 'object',
    properties: {
      id: { type: 'integer' },
      name: { type: 'string', example: 'Size' },
      option: { type: 'string', example: 'M' },
    },
  },

  ProductVariation: {
    type: 'object',
    description: 'A purchasable combination of attribute values belonging to a variable product.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 812 },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_modified: { type: 'string', format: 'date-time', readOnly: true },
      description: { type: 'string' },
      permalink: { type: 'string', format: 'uri', readOnly: true },
      sku: { type: 'string', example: 'TEE-NVY-M' },
      price: { type: 'string', readOnly: true },
      regular_price: { type: 'string', example: '1299.00' },
      sale_price: { type: 'string' },
      date_on_sale_from: { type: 'string', format: 'date-time', nullable: true },
      date_on_sale_to: { type: 'string', format: 'date-time', nullable: true },
      on_sale: { type: 'boolean', readOnly: true },
      status: { type: 'string', enum: ['draft', 'pending', 'private', 'publish'], default: 'publish' },
      purchasable: { type: 'boolean', readOnly: true },
      virtual: { type: 'boolean', default: false },
      downloadable: { type: 'boolean', default: false },
      downloads: { type: 'array', items: ref('ProductDownload') },
      download_limit: { type: 'integer', default: -1 },
      download_expiry: { type: 'integer', default: -1 },
      tax_status: { type: 'string', enum: ['taxable', 'shipping', 'none'], default: 'taxable' },
      tax_class: { type: 'string' },
      manage_stock: { oneOf: [{ type: 'boolean' }, { type: 'string', enum: ['parent'] }] },
      stock_quantity: { type: 'integer', nullable: true },
      stock_status: { type: 'string', enum: ['instock', 'outofstock', 'onbackorder'] },
      backorders: { type: 'string', enum: ['no', 'notify', 'yes'], default: 'no' },
      weight: { type: 'string' },
      dimensions: ref('Dimensions'),
      shipping_class: { type: 'string' },
      shipping_class_id: { type: 'integer', readOnly: true },
      image: ref('Image'),
      attributes: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string', example: 'Size' },
            option: { type: 'string', example: 'M' },
          },
        },
      },
      menu_order: { type: 'integer', default: 0 },
      meta_data: { type: 'array', items: ref('MetaData') },
      _links: ref('Links'),
    },
  },

  ProductCategory: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true, example: 19 },
      name: { type: 'string', example: 'Brewing' },
      slug: { type: 'string', example: 'brewing' },
      parent: { type: 'integer', default: 0 },
      description: { type: 'string' },
      display: {
        type: 'string',
        enum: ['default', 'products', 'subcategories', 'both'],
        default: 'default',
      },
      image: ref('Image'),
      menu_order: { type: 'integer', default: 0 },
      count: { type: 'integer', readOnly: true, description: 'Number of published products.' },
      _links: ref('Links'),
    },
    required: ['name'],
  },

  ProductTag: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true, example: 34 },
      name: { type: 'string', example: 'Gift ideas' },
      slug: { type: 'string', example: 'gift-ideas' },
      description: { type: 'string' },
      count: { type: 'integer', readOnly: true },
      _links: ref('Links'),
    },
    required: ['name'],
  },

  ProductAttribute: {
    type: 'object',
    description: 'A global (store-wide) attribute definition, e.g. Colour or Size.',
    properties: {
      id: { type: 'integer', readOnly: true, example: 3 },
      name: { type: 'string', example: 'Size' },
      slug: { type: 'string', example: 'pa_size' },
      type: { type: 'string', enum: ['select'], default: 'select' },
      order_by: {
        type: 'string',
        enum: ['menu_order', 'name', 'name_num', 'id'],
        default: 'menu_order',
      },
      has_archives: { type: 'boolean', default: false },
      _links: ref('Links'),
    },
    required: ['name'],
  },

  ProductAttributeTerm: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      name: { type: 'string', example: 'Medium' },
      slug: { type: 'string', example: 'medium' },
      description: { type: 'string' },
      menu_order: { type: 'integer' },
      count: { type: 'integer', readOnly: true },
      _links: ref('Links'),
    },
    required: ['name'],
  },

  ProductShippingClass: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      name: { type: 'string', example: 'Fragile' },
      slug: { type: 'string', example: 'fragile' },
      description: { type: 'string' },
      count: { type: 'integer', readOnly: true },
      _links: ref('Links'),
    },
    required: ['name'],
  },

  ProductReview: {
    type: 'object',
    properties: {
      id: { type: 'integer', readOnly: true },
      date_created: { type: 'string', format: 'date-time', readOnly: true },
      date_created_gmt: { type: 'string', format: 'date-time', readOnly: true },
      product_id: { type: 'integer', example: 799 },
      product_name: { type: 'string', readOnly: true },
      product_permalink: { type: 'string', format: 'uri', readOnly: true },
      status: {
        type: 'string',
        enum: ['approved', 'hold', 'spam', 'unspam', 'trash', 'untrash'],
        default: 'approved',
      },
      reviewer: { type: 'string', example: 'Asha Iyer' },
      reviewer_email: { type: 'string', format: 'email' },
      review: { type: 'string', example: 'Brews beautifully. Packaging could be better.' },
      rating: { type: 'integer', minimum: 0, maximum: 5, example: 4 },
      verified: { type: 'boolean', readOnly: true },
      reviewer_avatar_urls: { type: 'object', additionalProperties: { type: 'string' }, readOnly: true },
      _links: ref('Links'),
    },
    required: ['product_id', 'review', 'reviewer', 'reviewer_email'],
  },
} as const;
